name: my_chat_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  riverpod_generator: ^2.4.0
  riverpod_annotation: ^2.3.5
  build_runner: ^2.4.11
  firebase_core: ^2.27.0
  firebase_analytics: ^10.10.7
  google_sign_in: ^6.2.1
  firebase_auth: ^4.20.0
  sign_in_button: ^3.2.0
  cloud_firestore: ^4.17.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.2
  json_serializable: ^6.8.0
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.14
  ulid: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
