// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByJomtNJYOZUel3UZQAjpwjb_nGyd9uqM',
    appId: '1:216111928446:web:ea87ad4c6fbdb8f974742f',
    messagingSenderId: '216111928446',
    projectId: 'flutter-chat-app-a219c',
    authDomain: 'flutter-chat-app-a219c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a219c.appspot.com',
    measurementId: 'G-Q4TSXSMT3D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpIbWanAnZn7XKOjV855jYQyGNiqTclM',
    appId: '1:216111928446:ios:8db857a96d8d392674742f',
    messagingSenderId: '216111928446',
    projectId: 'flutter-chat-app-a219c',
    storageBucket: 'flutter-chat-app-a219c.appspot.com',
    iosClientId: '216111928446-6pg20lcb6plnpoft1kd86dht63qq5l6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChpIbWanAnZn7XKOjV855jYQyGNiqTclM',
    appId: '1:216111928446:ios:8db857a96d8d392674742f',
    messagingSenderId: '216111928446',
    projectId: 'flutter-chat-app-a219c',
    storageBucket: 'flutter-chat-app-a219c.appspot.com',
    iosClientId: '216111928446-6pg20lcb6plnpoft1kd86dht63qq5l6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByJomtNJYOZUel3UZQAjpwjb_nGyd9uqM',
    appId: '1:216111928446:web:f500c990319c7fbd74742f',
    messagingSenderId: '216111928446',
    projectId: 'flutter-chat-app-a219c',
    authDomain: 'flutter-chat-app-a219c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a219c.appspot.com',
    measurementId: 'G-Y233N3J5M9',
  );
}
